// <auto-generated />
using System;
using Base.Infra.Contextos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Base.Infra.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Base.Domain.Entidades.Assunto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnName("Descricao")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("assunto");
                });

            modelBuilder.Entity("Base.Domain.Entidades.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("Nome")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("autor");
                });

            modelBuilder.Entity("Base.Domain.Entidades.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AnoPublicacao")
                        .IsRequired()
                        .HasColumnName("AnoPublicacao")
                        .HasMaxLength(40);

                    b.Property<int>("Edicao")
                        .HasColumnName("Edicao");

                    b.Property<string>("Editora")
                        .IsRequired()
                        .HasColumnName("Editora")
                        .HasMaxLength(40);

                    b.Property<decimal>("Preco")
                        .HasColumnName("Preco");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnName("Titulo")
                        .HasMaxLength(40);

                    b.HasKey("Id");

                    b.ToTable("livro");
                });

            modelBuilder.Entity("Base.Domain.Entidades.LivroAssunto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AssuntoId");

                    b.Property<int?>("Assunto_Id");

                    b.Property<int?>("LivroId");

                    b.Property<int?>("Livro_Id");

                    b.HasKey("Id");

                    b.HasIndex("AssuntoId");

                    b.HasIndex("LivroId");

                    b.ToTable("LivroAssunto");
                });

            modelBuilder.Entity("Base.Domain.Entidades.LivroAutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Autor_Id")
                        .IsRequired();

                    b.Property<int?>("Livro_Id")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("Autor_Id");

                    b.HasIndex("Livro_Id");

                    b.ToTable("LivroAutor");
                });

            modelBuilder.Entity("Base.Domain.Entidades.LivroAssunto", b =>
                {
                    b.HasOne("Base.Domain.Entidades.Assunto", "Assunto")
                        .WithMany("LivroAssuntos")
                        .HasForeignKey("AssuntoId");

                    b.HasOne("Base.Domain.Entidades.Livro", "Livro")
                        .WithMany("LivroAssuntos")
                        .HasForeignKey("LivroId");
                });

            modelBuilder.Entity("Base.Domain.Entidades.LivroAutor", b =>
                {
                    b.HasOne("Base.Domain.Entidades.Autor", "Autor")
                        .WithMany("LivroAutors")
                        .HasForeignKey("Autor_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Base.Domain.Entidades.Livro", "Livro")
                        .WithMany("LivroAutors")
                        .HasForeignKey("Livro_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
